// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2bJ_35OLULPe3b8eyAlmUmuEBMMLpUFo',
    appId: '1:532336033127:web:16dfb183b1774f8b1d03c2',
    messagingSenderId: '532336033127',
    projectId: 'keuken-mobile-fc114',
    authDomain: 'keuken-mobile-fc114.firebaseapp.com',
    storageBucket: 'keuken-mobile-fc114.firebasestorage.app',
    measurementId: 'G-3EFSF4TQPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NmLAbJL3j8oT8mAjQAxxb3s4o85_GNE',
    appId: '1:532336033127:android:5540736ef2d178561d03c2',
    messagingSenderId: '532336033127',
    projectId: 'keuken-mobile-fc114',
    storageBucket: 'keuken-mobile-fc114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwr73hiQUcKf6ozP5578YiDb9Hf1xZXk',
    appId: '1:532336033127:ios:e8c0a1113aed8f251d03c2',
    messagingSenderId: '532336033127',
    projectId: 'keuken-mobile-fc114',
    storageBucket: 'keuken-mobile-fc114.firebasestorage.app',
    iosBundleId: 'com.example.puntoVentaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2bJ_35OLULPe3b8eyAlmUmuEBMMLpUFo',
    appId: '1:532336033127:web:53b958f025628a4e1d03c2',
    messagingSenderId: '532336033127',
    projectId: 'keuken-mobile-fc114',
    authDomain: 'keuken-mobile-fc114.firebaseapp.com',
    storageBucket: 'keuken-mobile-fc114.firebasestorage.app',
    measurementId: 'G-GGBTH5XWQE',
  );
}
